services:
  # If the app needs to be started via docker compose, uncomment these lines of code and add a Dockerfile 
  # app:
  #   tty: true
  #   stdin_open: true
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     target: development
  #   volumes:
  #     - .:/home/node/app
  #   ports:
  #     - "5173:5173"
  nostr-relay:
    image: scsibug/nostr-rs-relay:latest
    ports:
      - "7011:8080"
    volumes:
      - db:/usr/src/app/db:z
      - ./docker-relay-config.toml:/usr/src/app/config.toml
    environment:
      - RUST_LOG=debug

volumes:
  db: