# Server settings
[server]
host = "0.0.0.0"
port = 8080

# Relay info
[info]
name = "Dev Nostr Relay"
description = "A minimal public Nostr relay"
pubkey = ""
contact = "you@example.com"

# Database
[database]
data_directory = "/usr/src/app/db"

# Logging
[logging]
level = "info"

# Limits
[limits]
# Explicitly allow these event kinds
# 0: Metadata, 1: Text Note, 5: Event Deletion, 30000: Categorized People List
# 30301: Kanban Board, 30302: Kanban Card, 30303: Kanban Snapshot, 20001: Ephemeral Soft Lock
# 8571: Column Order Patch (Editor-Safe, keine 30301 Forks)
# 30023: Long Text
# 30142: Nostr Learning Resource
event_kind_allowlist = [0, 1, 5, 7, 11, 1111, 1985, 8571, 30000, 30301, 30302, 30303, 30023, 20001, 30142, 10222, 30222]

